=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/phantomAI.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (ClassObject)*>
<!ELEMENT ClassObject (ai_type|henna|nuke_skills|rare_nuke_skills|self_buff_skills|situation_skills|ultimate_self_buff_skills|debuff_skills|rare_debuff_skills|passive_skills|consumble_skills)*>
<!ATTLIST ClassObject
	classId CDATA #REQUIRED
	className CDATA #REQUIRED
	sex CDATA#REQUIRED>
<!ELEMENT ai_type (#PCDATA)>
<!ATTLIST ai_type
	type CDATA #REQUIRED
	sub_type CDATA #REQUIRED>
<!ELEMENT henna (#PCDATA)>
<!ATTLIST henna
	id CDATA #REQUIRED>
<!ELEMENT nuke_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT rare_nuke_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT self_buff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT situation_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	target CDATA #IMPLIED
	cond CDATA #IMPLIED>
<!ELEMENT ultimate_self_buff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT debuff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT rare_debuff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT passive_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT consumble_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	target CDATA #IMPLIED
	cond CDATA #IMPLIED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/Hierophant.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- ПП -->
	 
	<ClassObject classId="98" className="Hierophant" sex="1">
		<ai_type type="b_mystic" sub_type="stupid" />
		<henna id1="180" id2="171"/>
		<heal_skills>
			<skill id="1015" level="15" /> <!-- Battle Heal -->
		</heal_skills>
		<percent_heal_skills>
			<!-- Нету -->
		</percent_heal_skills>
		<self_buff_skills>
			<!-- Нету -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<skill id="1411" level="1" /> <!-- Mystic Immunity -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="1201" level="33" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Dryad Root -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="1398" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>  <!-- Mana Burn -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="632" level="6" /> <!-- Emergent Ability - Defence -->
			<skill id="652" level="1" /> <!-- Knight Ability - Defense -->
			<skill id="655" level="1" /> <!-- Enchanter Ability - Barrier -->
			<skill id="1491" level="1" /> <!-- Summoner Ability - Spirit -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/ai/FortuneSeeker.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- Спойлер -->
	 
	<ClassObject classId="117" className="Fortune Seeker" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<henna id1="169" id2="30"/>
		<nuke_skills>
		    <skill id="260" level="37" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="6"/> <!-- Armor Crush -->
			<skill id="995" level="1" /> <!-- Rush Impact -->
			<skill id="947" level="1" />	<!-- Lucky Strike -->
			<skill id="997" level="25" />	<!-- Crushing Strike -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="362" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="3"/> <!-- Armor Crush -->
		</rare_nuke_skills>
		<self_buff_skills>
			 <!-- Нету -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<skill id="917" level="1" /> <!-- Final Secret -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="362" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="3"/> <!-- Armor Crush -->
		</debuff_skills>
		<rare_debuff_skills>
			<!-- Нету -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>
