=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/phantomAI.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (ClassObject)*>
<!ELEMENT ClassObject (ai_type|henna|nuke_skills|rare_nuke_skills|self_buff_skills|situation_skills|ultimate_self_buff_skills|debuff_skills|rare_debuff_skills|passive_skills|consumble_skills)*>
<!ATTLIST ClassObject
	classId CDATA #REQUIRED
	className CDATA #REQUIRED
	sex CDATA#REQUIRED>
<!ELEMENT ai_type (#PCDATA)>
<!ATTLIST ai_type
	type CDATA #REQUIRED
	sub_type CDATA #REQUIRED>
<!ELEMENT henna (#PCDATA)>
<!ATTLIST henna
	id CDATA #REQUIRED>
<!ELEMENT nuke_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT rare_nuke_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT self_buff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT situation_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	target CDATA #IMPLIED
	cond CDATA #IMPLIED>
<!ELEMENT ultimate_self_buff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT debuff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	is_enchantable CDATA #IMPLIED
	is_random CDATA #IMPLIED
	ench_max_value CDATA #REQUIRED
	ench_route CDATA #REQUIRED>
<!ELEMENT rare_debuff_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT passive_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT consumble_skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	target CDATA #IMPLIED
	cond CDATA #IMPLIED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/SwordMuse.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- СвС -->
	 
	<ClassObject classId="100" className="Sword Muse" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<henna id1="169" id2="30"/>
		<nuke_skills>
			<skill id="986" level="25" /> <!-- Deadly Strike -->
		</nuke_skills>
		<rare_nuke_skills>
			<!-- Нету -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="988" level="3" /> <!-- Battle Whisper -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<!-- Нету -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="98" level="5" />	<!-- Sword Symphony -->
			<skill id="407" level="10" /> <!-- Psycho Symphony -->
			<skill id="402" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Arrest -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="437" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="1"/> <!-- Song of Silence -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" cond="MP;50"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" cond="CP;90"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/SpectralDancer.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- БД -->
	 
	<ClassObject classId="107" className="Spectral Dancer" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<henna id1="169" id2="30"/>
		<nuke_skills>
			<skill id="986" level="25" /> <!-- Deadly Strike -->
		</nuke_skills>
		<rare_nuke_skills>
			<!-- Нету -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="989" level="1" /> <!-- Defense Motion -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<!-- Нету -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="84" level="3" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>	<!-- Poison Blade Dance -->
			<skill id="408" level="10" />	<!-- Demonic Blade Dance -->
			<skill id="402" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Arrest -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="122" level="15" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Hex -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/ai/SpectralMaster.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- ФС -->
	 
	<ClassObject classId="111" className="Spectral Master" sex="1">
		<ai_type type="b_mystic" sub_type="stupid" />
		<henna id1="180" id2="171"/>
		<nuke_skills>
			<skill id="1530" level="13" /> <!-- Death Spike FSa -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="1558" level="24" /> <!-- Dimension Spiral -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="1547" level="3" /> <!-- Spirit Sharing -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			 <!-- Нету -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="1350" level="1" /> <!-- Warrior Bane -->
			<skill id="1351" level="1" /> <!-- Mage Bane -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="1386" level="10" /> <!-- Arcane Disruption -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="632" level="6" /> <!-- Emergent Ability - Defence -->
			<skill id="652" level="1" /> <!-- Knight Ability - Defense -->
			<skill id="655" level="1" /> <!-- Enchanter Ability - Barrier -->
			<skill id="1491" level="1" /> <!-- Summoner Ability - Spirit -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1"/> <!-- CP Potion Low, бот использует когда CP меньше 10% пока СР не будет 50% заполнено -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/WindRider.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>
     <!-- ПВ -->
	 
	<ClassObject classId="101" className="WindRider" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<henna id1="169"/>
		<nuke_skills>
			<skill id="263" level="37" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="7"/> <!-- Deadly Blow -->
			<skill id="344" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="7"/> <!-- Lethal Blow -->
			<skill id="321" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>  <!-- Blinding Blow -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="321" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>  <!-- Blinding Blow -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="355" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="2"/>	 <!-- Focus Death -->
			<skill id="410" level="3" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Mortal Strike -->
		</self_buff_skills>
		<situation_skills>
			<skill id="769" level="1" target="self" cond="hp;70;0"/> <!-- Wind Riding -->
		</situation_skills>
		<ultimate_self_buff_skills>
			<skill id="111" level="1" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Ultimate Evasion -->
			<skill id="922" level="1" /> <!-- Hide -->
			<skill id="446" level="1" /> <!-- Dodge -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="358" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="1"/> <!-- Bluff -->
			<skill id="531" level="1" /> <!-- Critical Wound -->
			<skill id="821" level="1" /> <!-- Shadow Step -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="991" level="1" /> <!-- Throw Dagger -->
			<skill id="821" level="1" />	<!-- Shadow Step -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
			<skill id="26074" level="10" />	<!-- Bot Vicious Stance -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/ai/Soultaker.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- Некар -->
	 
	<ClassObject classId="95" className="Soultaker" sex="1">
		<ai_type type="b_mystic" sub_type="stupid" />
		<henna id1="180" id2="171" id3="175"/>
		<nuke_skills>
			<skill id="1148" level="13" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Death Spike -->
			<skill id="1234" level="28" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Vampiric Claw -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="1467" level="1" /> <!-- Meteor -->
		</rare_nuke_skills>
		<self_buff_skills>
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<skill id="1532" level="1" /> <!-- Enlightenment -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="1160" level="15" />	<!-- Slow -->
			<skill id="1169" level="14" /> <!-- Curse Fear -->
			<skill id="1170" level="13" /> <!-- Anchor -->
			<skill id="1495" level="1" />	<!-- Vampiric Mist -->
			<skill id="1336" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="1" /> <!-- Curse of Doom -->
			<skill id="1263" level="13" /> <!-- Curse Gloom -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="1343" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="3"/> <!-- Dark Vortex -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="632" level="6" /> <!-- Emergent Ability - Defence -->
			<skill id="652" level="1" /> <!-- Knight Ability - Defense -->
			<skill id="655" level="1" /> <!-- Enchanter Ability - Barrier -->
			<skill id="1491" level="1" /> <!-- Summoner Ability - Spirit -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/ai/ShillienTemplar.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- ШК -->
	 
	<ClassObject classId="106" className="Shillien Templar" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<nuke_skills>
			<skill id="401" level="15" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Jugdment -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="984" level="25" /> <!-- Shield Strike -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="351" level="1" /> <!-- Magical Mirror -->
			<skill id="913" level="1" /> <!-- Deflect Magic -->
			<skill id="982" level="3" /> <!-- Combat Aura -->
			<skill id="527" level="1" /> <!-- Iron Shield -->
			<skill id="788" level="1" /> <!-- Pain of Shilen -->
		</self_buff_skills>
		<situation_skills>
			<skill id="789" level="1" target="self" cond="skill;5564;3"/> <!-- Spirit os Shilen -->
			<skill id="528" level="1" target="self" cond="hp;70;0"/> <!-- Shield of Faith -->
		</situation_skills>
		<ultimate_self_buff_skills>
			<skill id="916" level="4" /> <!-- Shield Deflect Magic -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="122" level="15" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Hex -->
			<!-- <skill id="28" level="49" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/>  Aggression -->
			<skill id="402" level="10" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="2"/> <!-- Arrest -->
			<skill id="279" level="5" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="3"/> <!-- Lightning Strike -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="985" level="1" /> <!-- Challenge for Fate -->
			<skill id="352" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="1"/> <!-- Shield Bash -->
			<skill id="342" level="1" is_enchantable="true" is_random="false" ench_max_value="15" ench_route="1"/> <!-- Touch of Death -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/Dreadnought.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- Варлорд -->
	 
	<ClassObject classId="89" className="Dreadnought" sex="1">
		<ai_type type="b_fighter" sub_type="stupid" />
		<henna id1="169" id2="30"/>
		<nuke_skills>
			<skill id="995" level="1" /> <!-- Rush Impact -->
			<skill id="48" level="37" /> <!-- Thunder Storm -->
			<skill id="921" level="1" /> <!-- Cursed Pierce -->
		</nuke_skills>
		<rare_nuke_skills>
			<skill id="347" level="1" /> <!-- Earthquake -->
		</rare_nuke_skills>
		<self_buff_skills>
			<skill id="78" level="2" />	<!-- War Cry -->
			<skill id="130" level="2" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Thrill Fight -->
		</self_buff_skills>
		<situation_skills>
			<skill id="181" level="1" target="self" cond="hp;10;0"/> <!-- Revival -->
		</situation_skills>
		<ultimate_self_buff_skills>
			<skill id="917" level="1" /> <!-- Final Secret -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="361" level="1" />	<!-- Shock Blast -->
			<skill id="452" level="5" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>	<!-- Shock Stomp -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="116" level="14" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/>	<!-- Howl -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="631" level="6" />	<!-- Emergent Ability - Attack -->
			<skill id="652" level="1" />	<!-- Knight Ability - Defense -->
			<skill id="655" level="1" />	<!-- Enchanter Ability - Barrier -->
			<skill id="651" level="1" />	<!-- Warrior Ability - Haste -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/ai/ShillienSaint.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomAI.dtd">
<list>

     <!-- СЕ -->
	 
	<ClassObject classId="112" className="Shillien Saint" sex="1">
		<ai_type type="b_mystic" sub_type="stupid" />
		<henna id1="180" id2="171"/>
		<heal_skills>
			<skill id="1217" level="33" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Heal -->
		</heal_skills>
		<percent_heal_skills>
			<skill id="1553" level="1" /> <!-- Chain Heal -->
		</percent_heal_skills>
		<self_buff_skills>
			<!-- Нету -->
		</self_buff_skills>
		<ultimate_self_buff_skills>
			<!-- Нету -->
		</ultimate_self_buff_skills>
		<debuff_skills>
			<skill id="1201" level="33" is_enchantable="true" is_random="false" ench_max_value="30" ench_route="1"/> <!-- Dryad Root -->
		</debuff_skills>
		<rare_debuff_skills>
			<skill id="1539" level="4" /> <!-- Stigma of Shilen -->
		</rare_debuff_skills>
		<passive_skills>
			<skill id="632" level="6" /> <!-- Emergent Ability - Defence -->
			<skill id="652" level="1" /> <!-- Knight Ability - Defense -->
			<skill id="655" level="1" /> <!-- Enchanter Ability - Barrier -->
			<skill id="1491" level="1" /> <!-- Summoner Ability - Spirit -->
		</passive_skills>
		<consumble_skills>
			<skill id="6439" level="1" target="self" cond="MP;50;0"/> <!-- MP Potion, бот использует когда MP меньше 50% один раз -->
			<skill id="2166" level="1" target="self" cond="CP;90;0"/> <!-- CP Potion Low, бот использует когда CP меньше 90% -->
		</consumble_skills>
	</ClassObject>
 </list>
