=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/sets/phantomSets.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (BotSetObject)*>
<!ELEMENT BotSetObject (helm|chest|gaiter|gloves|boots|shirt|belt|shield|male_hat|female_hat|cloak)*>
<!ATTLIST BotSetObject
	classId CDATA #REQUIRED
	className CDATA #REQUIRED>
<!ELEMENT helm (#PCDATA)>
<!ATTLIST helm
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	is_att_random CDATA #IMPLIED>
<!ELEMENT chest (#PCDATA)>
<!ATTLIST chest
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	is_att_random CDATA #IMPLIED>
<!ELEMENT gaiter (#PCDATA)>
<!ATTLIST gaiter
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	is_att_random CDATA #IMPLIED>
<!ELEMENT gloves (#PCDATA)>
<!ATTLIST gloves
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	is_att_random CDATA #IMPLIED>
<!ELEMENT boots (#PCDATA)>
<!ATTLIST boots
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	is_att_random CDATA #IMPLIED>
<!ELEMENT shirt (#PCDATA)>
<!ATTLIST shirt
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT belt (#PCDATA)>
<!ATTLIST belt
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT shield (#PCDATA)>
<!ATTLIST shield
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT male_hat (#PCDATA)>
<!ATTLIST male_hat
	id CDATA #REQUIRED
	chance CDATA #REQUIRED>
<!ELEMENT female_hat (#PCDATA)>
<!ATTLIST female_hat
	id CDATA #REQUIRED
	chance CDATA #REQUIRED>
<!ELEMENT cloak (#PCDATA)>
<!ATTLIST cloak
	id CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/sets/Hierophant.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomSets.dtd">
<list>
	<BotSetObject classId="98" className="Hierophant"> <!-- Роба Нубл Веспера -->
		<helm id="13142" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<chest id="14525" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gaiter id="13454" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gloves id="13455" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<boots id="13456" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<shirt id="10512" enchant="6" is_random="false"/>
		<belt id="14961" enchant="6" is_random="false"/>
        <shield id="12813" enchant="6" is_random="false"/>		
		<male_hat id="8660" chance="30"/> <!-- Шапка для Мужчин -->
		<female_hat id="7683" chance="30"/> <!-- Шапка для Женщин -->
		<cloak id="21718" chance="100"/>		
	</BotSetObject>
	<BotSetObject classId="98" className="Hierophant"> <!-- Роба Дестино -->
		<helm id="15608" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<chest id="16176" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gaiter id="15614" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gloves id="15617" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<boots id="15620" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<shirt id="10512" enchant="6" is_random="false"/>
		<belt id="14961" enchant="6" is_random="false"/>
        <shield id="15622" enchant="6" is_random="false"/>		
		<male_hat id="8660" chance="30"/> <!-- Шапка для Мужчин -->
		<female_hat id="7683" chance="30"/> <!-- Шапка для Женщин -->
		<cloak id="21717" chance="100"/>		
	</BotSetObject>
	<BotSetObject classId="98" className="Hierophant"> <!-- Роба Верпеса -->
		<helm id="15591" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<chest id="16173" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gaiter id="15597" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<gloves id="15600" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<boots id="15603" enchant="6" is_random="false" attribute_min="120" attribute_max="120" is_att_random="false"/>
		<shirt id="10512" enchant="6" is_random="false"/>
		<belt id="14961" enchant="6" is_random="false"/>
        <shield id="15605" enchant="6" is_random="false"/>		
		<male_hat id="8660" chance="30"/> <!-- Шапка для Мужчин -->
		<female_hat id="7683" chance="30"/> <!-- Шапка для Женщин -->
		<cloak id="21716" chance="100"/>		
	</BotSetObject>
 </list>
