=== destruccionloca/L2Emurt-H5/dist/gameserver/data/xml/superpoint/superpoint.dtd
<!ELEMENT list (superpoint)*>
<!ELEMENT superpoint (node)*>
<!ATTLIST superpoint
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	is_running CDATA #IMPLIED>
<!ELEMENT node (#PCDATA)>
<!ATTLIST node
	chat_type CDATA #IMPLIED
	delay CDATA #IMPLIED
	npc_string CDATA #IMPLIED
	social CDATA #IMPLIED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/data/xml/superpoint/superpoint.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "superpoint.dtd">
<!-- 
	type: Виды перемещения
	
	CIRCLE, // после окончания маршрута сразу же начинает его с начала
	LOOP, // после окончания маршрута возвращается по нему же в обратную сторону
	DELETE, // после окончания маршрута удаляется и запускается респавн
	FINISH, // после окончания маршрута нпц останавливается
	RANDOM // следующая точка маршрута выбирается случайно
	
 -->

<list>
	<superpoint name="scribe_leandro" type="LOOP">
		<node x="-82428" y="245204" z="-3712"/>
		<node x="-82198" y="245361" z="-3712"/>
		<node x="-82091" y="245028" z="-3720"/>
		<node x="-82381" y="244911" z="-3720"/>
		<node x="-82935" y="244481" z="-3728"/>
		<node x="-83980" y="242776" z="-3728" npc_string="WHERE_HAS_HE_GONE" chat_type="ALL" delay="10"/>
		<node x="-85966" y="241371" z="-3728"/>
		<node x="-86079" y="240868" z="-3720" npc_string="HAVE_YOU_SEEN_WINDAWOOD" chat_type="ALL"  delay="5"/>
		<node x="-86076" y="240392" z="-3712"/>
		<node x="-86519" y="240706" z="-3704"/>
		<node x="-86343" y="241130" z="-3728" npc_string="WHERE_DID_HE_GO" chat_type="ALL"  delay="60"/>
	</superpoint>
	<superpoint name="porter_remy" type="CIRCLE" is_running="true"> <!-- Remy всегда бегает -->
		<node x="-81926" y="243894" z="-3712" delay="3"/>
		<node x="-82134" y="243600" z="-3728"/>
		<node x="-83182" y="243723" z="-3728"/>
		<node x="-84486" y="243236" z="-3728" npc_string="I_NEED_A_BREAK" chat_type="ALL" delay="5"/>
		<node x="-85205" y="243187" z="-3728"/>
		<node x="-86152" y="242898" z="-3728"/>
		<node x="-86288" y="242962" z="-3720"/>
		<node x="-86352" y="243207" z="-3720" npc_string="HELLO_MR" chat_type="ALL" delay="5"/>
		<node x="-86501" y="242762" z="-3720"/>
		<node x="-86500" y="242615" z="-3728"/>
		<node x="-86123" y="241606" z="-3728"/>
		<node x="-85207" y="240698" z="-3728"/>
		<node x="-84066" y="241285" z="-3728" npc_string="LULU" chat_type="ALL" delay="5"/>
		<node x="-83215" y="241170" z="-3728"/>
		<node x="-82364" y="242944" z="-3720"/>
		<node x="-81674" y="243391" z="-3712" npc_string="A_DELIVERY_FOR_MR" chat_type="ALL" delay="60"/>
		<node x="-81926" y="243894" z="-3712"/>
	</superpoint>
	<superpoint name="flame_keeper_yakand" type="CIRCLE">
		<node x="-48820" y="-113748" z="-232"/>
		<node x="-47365" y="-113618" z="-224"/>
		<node x="-45678" y="-113635" z="-240"/>
		<node x="-45168" y="-114038" z="-224"/>
		<node x="-44671" y="-114185" z="-240"/>
		<node x="-44199" y="-113763" z="-240"/>
		<node x="-44312" y="-113201" z="-240"/>
		<node x="-44844" y="-112958" z="-240"/>
		<node x="-45717" y="-113564" z="-240"/>
		<node x="-47370" y="-113588" z="-224"/>
		<node x="-48821" y="-113496" z="-232" delay="10"/>
		<node x="-48820" y="-113748" z="-232"/>
	</superpoint>
	<superpoint name="flame_keeper_lokar" type="LOOP">
		<node x="-46516" y="-117700" z="-240"/>
		<node x="-45550" y="-115420" z="-240"/>
		<node x="-44052" y="-114575" z="-240"/>
		<node x="-44024" y="-112688" z="-240"/>
		<node x="-45748" y="-111665" z="-240"/>
		<node x="-46512" y="-109390" z="-208" delay="5"/>
	</superpoint>
	<superpoint name="tetrarch_exec_creed" type="CIRCLE" is_running="true">
		<node x="23436" y="11164" z="-3720"/>
		<node x="20256" y="11104" z="-3720"/>
		<node x="17330" y="13579" z="-3728"/>
		<node x="17415" y="13044" z="-3736" npc_string="THE_MASS_OF_DARKNESS_WILL_START_IN_A_COUPLE_OF_DAYS" chat_type="ALL" delay="10"/>
		<node x="20153" y="12880" z="-3712"/>
		<node x="21621" y="13349" z="-3624"/>
		<node x="20686" y="10432" z="-3712"/>
		<node x="22426" y="10260" z="-3648"/>
		<node x="23436" y="11164" z="-3720"/>
	</superpoint>
	<superpoint name="bard_casiel" type="LOOP">
		<node x="43932" y="51096" z="-2992"/>
		<node x="43304" y="50364" z="-2992"/>
		<node x="43041" y="49312" z="-2992"/>
		<node x="43612" y="48322" z="-2992"/>
		<node x="44009" y="47645" z="-2992"/>
		<node x="45309" y="47341" z="-2992" npc_string="THE_MOTHER_TREE_IS_ALWAYS_SO_GORGEOUS" chat_type="ALL" delay="5"/>
		<node x="46726" y="47762" z="-2992"/>
		<node x="47509" y="49004" z="-2992"/>
		<node x="47443" y="50456" z="-2992"/>
		<node x="47013" y="51287" z="-2992" npc_string="LADY_MIRABEL_MAY_THE_PEACE_OF_THE_LAKE_BE_WITH_YOU" chat_type="ALL" delay="60"/>
	</superpoint>
	<superpoint name="treekeeper_jaradine" type="LOOP">
		<node x="44964" y="50568" z="-3056"/>
		<node x="44435" y="50025" z="-3056"/>
		<node x="44455" y="49078" z="-3056"/>
		<node x="45402" y="48437" z="-3056" npc_string="THE_MOTHER_TREE_IS_SLOWLY_DYING" chat_type="ALL" delay="5"/>
		<node x="46104" y="48788" z="-3056" npc_string="HOW_CAN_WE_SAVE_THE_MOTHER_TREE" chat_type="ALL" delay="5"/>
		<node x="46452" y="49743" z="-3056"/>
		<node x="45730" y="50590" z="-3056" delay="60"/>
	</superpoint>
	<superpoint name="messenger_rogin" type="CIRCLE" is_running="true">
		<node x="115744" y="-183424" z="-1472" delay="60"/>
		<node x="115878" y="-183267" z="-1472"/>
		<node x="116116" y="-183090" z="-1496"/>
		<node x="116587" y="-184306" z="-1568" npc_string="HAVE_YOU_SEEN_TOROCCO_TODAY" chat_type="ALL" delay="10"/>
		<node x="116392" y="-184090" z="-1560"/>
		<node x="117083" y="-182538" z="-1520"/>
		<node x="117802" y="-182541" z="-1528" npc_string="HAVE_YOU_SEEN_TOROCCO" chat_type="ALL" delay="10"/>
		<node x="116720" y="-182479" z="-1512" npc_string="WHERE_IS_THAT_FOOL_HIDING" chat_type="ALL" delay="10"/>
		<node x="115857" y="-183287" z="-1472"/>
		<node x="115744" y="-183424" z="-1472"/>
	</superpoint>
	<superpoint name="porter_tate" type="CIRCLE">
		<node x="115824" y="-181564" z="-1336" delay="20"/>
		<node x="116048" y="-181575" z="-1352" npc_string="CARE_TO_GO_A_ROUND" chat_type="ALL"/>
		<node x="116521" y="-181476" z="-1384"/>
		<node x="116632" y="-180022" z="-1160"/>
		<node x="115355" y="-178617" z="-928"/>
		<node x="115763" y="-177585" z="-888"/>
		<node x="115795" y="-177361" z="-880" npc_string="HAVE_A_NICE_DAY_MR" chat_type="ALL"/>
		<node x="115877" y="-177338" z="-880" delay="15"/>
		<node x="115783" y="-177493" z="-880"/>
		<node x="115112" y="-179836" z="-880"/>
		<node x="115102" y="-180026" z="-872"/>
		<node x="114876" y="-180045" z="-872" npc_string="MR" chat_type="ALL" delay="30"/>
		<node x="114840" y="-179694" z="-872"/>
		<node x="116322" y="-179602" z="-1088"/>
		<node x="116792" y="-180386" z="-1200"/>
		<node x="116319" y="-181573" z="-1384"/>
		<node x="115824" y="-181564" z="-1336"/>
	</superpoint>
	<superpoint name="running_boy" type="LOOP">
		<node x="84416" y="-144052" z="-1528" delay="5"/>
		<node x="84460" y="-142495" z="-1536"/>
		<node x="85242" y="-140949" z="-1536"/>
		<node x="87362" y="-140059" z="-1536" delay="5"/>
		<node x="89350" y="-140750" z="-1536"/>
		<node x="90607" y="-143176" z="-1536"/>
		<node x="90267" y="-143883" z="-1536" delay="5"/>
	</superpoint>
	<superpoint name="tetrarch_agent_alhena" type="CIRCLE">
		<node x="10968" y="14620" z="-4240"/>
		<node x="11308" y="15847" z="-4584"/>
		<node x="12119" y="16441" z="-4584"/>
		<node x="15104" y="15661" z="-4376" npc_string="YOURE_A_HARD_WORKER_RAYLA" chat_type="ALL" delay="5"/>
		<node x="15265" y="16288" z="-4376"/>
		<node x="12292" y="16934" z="-4584"/>
		<node x="11777" y="17669" z="-4584"/>
		<node x="11229" y="17650" z="-4568"/>
		<node x="10641" y="17282" z="-4584"/>
		<node x="7683" y="18034" z="-4376" npc_string="YOURE_A_HARD_WORKER_RAYLA" chat_type="ALL" delay="5"/>
		<node x="10551" y="16775" z="-4584"/>
		<node x="11004" y="15942" z="-4584"/>
		<node x="10827" y="14757" z="-4240"/>
		<node x="10968" y="14620" z="-4240"/>
	</superpoint>
	<superpoint name="rune_ghost1b" type="CIRCLE">
		<node x="51752" y="-54736" z="-3160"/>
		<node x="51998" y="-54685" z="-3160"/>
		<node x="52083" y="-54439" z="-3152"/>
		<node x="52296" y="-53194" z="-3152"/>
		<node x="51891" y="-51628" z="-3096" delay="15"/>
	</superpoint>
	<superpoint name="aden_fort_a_ordery" type="LOOP">
		<node x="159403" y="52418" z="-3312"/>
		<node x="161177" y="54083" z="-3560"/>
		<node x="162152" y="54365" z="-3632"/>
		<node x="162703" y="55840" z="-3696"/>
		<node x="162370" y="58534" z="-3504"/>
		<node x="160099" y="60034" z="-3224"/>
		<node x="158048" y="62696" z="-3464"/>
		<node x="157220" y="63450" z="-3520"/>
		<node x="155076" y="63731" z="-3544"/>
		<node x="153893" y="64441" z="-3656"/>
		<node x="153085" y="62948" z="-3680"/>
		<node x="153035" y="62296" z="-3688"/>
		<node x="150866" y="58737" z="-3432"/>
	</superpoint>
	<superpoint name="ore_gi_fort_ordery" type="CIRCLE">
		<node x="74810" y="90814" z="-3344"/>
		<node x="75094" y="92951" z="-3104"/>
		<node x="75486" y="92906" z="-3072"/>
		<node x="75765" y="91794" z="-2912"/>
		<node x="77116" y="90455" z="-2896"/>
		<node x="77743" y="89119" z="-2896"/>
		<node x="77118" y="90457" z="-2896"/>
		<node x="75750" y="91811" z="-2912"/>
		<node x="75479" y="92904" z="-3072"/>
		<node x="75094" y="92943" z="-3104"/>
		<node x="74809" y="90794" z="-3344"/>
		<node x="76932" y="88297" z="-3296"/>
		<node x="77882" y="87441" z="-3408"/>
		<node x="78257" y="85859" z="-3632"/>
		<node x="80994" y="85866" z="-3472"/>
		<node x="82676" y="87519" z="-3360"/>
		<node x="83778" y="88414" z="-3376"/>
		<node x="83504" y="90378" z="-3120"/>
		<node x="84431" y="90379" z="-3264"/>
		<node x="85453" y="90117" z="-3312"/>
		<node x="85605" y="89708" z="-3296"/>
		<node x="84894" y="88975" z="-3344"/>
		<node x="83735" y="88382" z="-3376"/>
		<node x="82616" y="87485" z="-3360"/>
		<node x="80971" y="85855" z="-3472"/>
		<node x="78247" y="85853" z="-3632"/>
		<node x="77868" y="87463" z="-3408"/>
		<node x="76916" y="88304" z="-3280"/>
		<node x="75494" y="89865" z="-3200"/>
	</superpoint>
	<superpoint name="gludio_fort_a_ordery" type="CIRCLE">
		<node x="-58672" y="154703" z="-2688"/>
		<node x="-58672" y="154703" z="-2688"/>
		<node x="-57522" y="156523" z="-2576"/>
		<node x="-55226" y="157117" z="-2064"/>
		<node x="-57528" y="156515" z="-2576"/>
