=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/weapons/phantomWeapon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (BotWeaponObject)*>
<!ELEMENT BotWeaponObject (weapon)*>
<!ATTLIST BotWeaponObject
	classId CDATA #REQUIRED
	className CDATA #REQUIRED>
<!ELEMENT weapon (#PCDATA)>
<!ATTLIST weapon
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #REQUIRED
	augment_chance  CDATA #IMPLIED
	attribute_min CDATA #REQUIRED
	attribute_max CDATA #REQUIRED
	attribute CDATA #REQUIRED
	is_att_random  CDATA #IMPLIED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/weapons/ArcanaLord.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomWeapon.dtd">
<list>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="14485" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="15968" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="16012" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="14502" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="15964" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="16005" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="21976" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32096" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32103" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32249" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32251" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32265" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32277" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="96" className="Arcana Lord">
		<weapon id="32279" enchant="10" is_random="false" augment_chance="50" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	
 </list>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/weapons/GhostSentinel.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomWeapon.dtd">
<list>	
	<BotWeaponObject classId="109" className="Ghost Sentinel">
		<weapon id="14509" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="15971" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="dark" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="16015" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="fire" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="32106" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="water" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="32252" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="wind" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="32266" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="earth" is_att_random="false"/>
	</BotWeaponObject>
	<BotWeaponObject classId="109" className="Moonlight Sentinel">
		<weapon id="32280" enchant="10" is_random="false" augment_chance="40" attribute_min="300" attribute_max="300" attribute="holy" is_att_random="false"/>
	</BotWeaponObject>
	
 </list>
