=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/spawn/phantomSpawn.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (SpawnObject)*>
<!ELEMENT SpawnObject (coord)*>
<!ATTLIST SpawnObject
	ai_type CDATA #REQUIRED
	is_spawn_enabled CDATA #IMPLIED
	description CDATA #REQUIRED>
<!ELEMENT coord (#PCDATA)>
<!ATTLIST coord
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	count CDATA #REQUIRED
	handicap_attack CDATA #REQUIRED
	handicap_defence CDATA #REQUIRED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/spawn/spawn_1_peace.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomSpawn.dtd">
<list>
     <!-- 
		peace   - Мирные боты гуляющие по городу.
		warrior - Боевые боты воины.
		dagger  - Боевые боты дагерщики.
		tank_a  - Боевые боты танки (забафаны полностью в атаку).
		tank_b  - Боевые боты танки (забафаны полностью в защиту).
		archer  - Боевые боты лучники.
		mage_a  - Боевые боты маги (забафаны полностью в атаку).
		mage_b  - Боевые боты маги (забафаны полностью в защиту).
		ghost   - Невидимки для накрутки онлайна.
	--> 
	<!--
		handicap_attack - в % указывается бонус атаки для этой группы ботов.
		handicap_defence - в % указывается бонус защиты для этой группы ботов.
		По умолчанию 100%.
		Может принимать значения от 5% до 300%.
		Можно не вписывать (тогда используется стандартное значение в 100%).
	-->
	<SpawnObject ai_type="peace" is_spawn_enabled="true" description="GiranAden">
		<coord x="-82600" y="150792" z="-3120" count="5" handicap_attack="0" handicap_defence="0"/>
		<coord x="-81800" y="150856" z="-3120" count="5" handicap_attack="0" handicap_defence="0"/>
    </SpawnObject>
    <SpawnObject ai_type="peace" is_spawn_enabled="true" description="GiranAden">
		<coord x="-80712" y="149896" z="-3040" count="5" handicap_attack="0" handicap_defence="0"/>
		<coord x="82904" y="148616" z="-3472" count="7" handicap_attack="0" handicap_defence="0"/>
		<coord x="-70408" y="-71080" z="-1416" count="8" handicap_attack="0" handicap_defence="0"/>
		<coord x="143800" y="146472" z="-12032" count="5" handicap_attack="0" handicap_defence="0"/>
		<coord x="144104" y="142920" z="-11880" count="3" handicap_attack="0" handicap_defence="0"/>
		<coord x="147224" y="146760" z="-12256" count="7" handicap_attack="0" handicap_defence="0"/>
		<coord x="-70680" y="-71192" z="-1416" count="5" handicap_attack="0" handicap_defence="0"/>
		<coord x="143672" y="143320" z="-11920" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="142520" y="143992" z="-11920" count="1" handicap_attack="0" handicap_defence="0"/>
		<coord x="148296" y="143640" z="-12224" count="1" handicap_attack="0" handicap_defence="0"/>
		<coord x="147960" y="143640" z="-12224" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="83416" y="148408" z="-3408" count="4" handicap_attack="0" handicap_defence="0"/>
		<coord x="184744" y="-77704" z="-2728" count="1" handicap_attack="0" handicap_defence="0"/>
		<coord x="185896" y="-75592" z="-2728" count="5" handicap_attack="0" handicap_defence="0"/>
		<coord x="183816" y="-78664" z="-2728" count="4" handicap_attack="0" handicap_defence="0"/>
		<coord x="18168" y="170312" z="-3525" count="4" handicap_attack="0" handicap_defence="0"/>
		<coord x="17176" y="170104" z="-3523" count="4" handicap_attack="0" handicap_defence="0"/>
		<!-- Aden -->
		<coord x="147448" y="26936" z="-2208" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="147464" y="28216" z="-2272" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="147464" y="30232" z="-2464" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="149928" y="27624" z="-2272" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="149832" y="24264" z="-2144" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="147432" y="21096" z="-2144" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="145176" y="24232" z="-2144" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="145000" y="27608" z="-2272" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="147464" y="25848" z="-2016" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="147464" y="23816" z="-1984" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="146056" y="28920" z="-2248" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="148792" y="28920" z="-2248" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="148808" y="26264" z="-2184" count="2" handicap_attack="0" handicap_defence="0"/>
		<coord x="150616" y="28296" z="-2248" count="2" handicap_attack="0" handicap_defence="0"/>
	</SpawnObject>
 </list>
