=== destruccionloca/L2Emurt-H5/dist/gameserver/data/xml/zone/zone.dtd
<!ELEMENT list (zone)*>
<!ELEMENT zone (polygon|circle|rectangle|banned_polygon|set|restart_point|PKrestart_point|doors)*>
<!ATTLIST zone
	name CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT polygon (coords)*>
<!ELEMENT circle (coords)*>
<!ELEMENT rectangle (coords)*>
<!ELEMENT restart_point (coords)*>
<!ELEMENT PKrestart_point (coords)*>
<!ELEMENT doors (door)*>
<!ELEMENT banned_polygon (coords)*>
<!ELEMENT coords (#PCDATA)>
<!ELEMENT door (#PCDATA)>
<!ATTLIST coords
	loc CDATA #REQUIRED>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ATTLIST circle
	loc CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	val CDATA #REQUIRED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/data/xml/zone/no_summon.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>
	<zone name="[MDT_no_summon]" type="no_summon">
		<polygon>
			<coords loc="14440 181273"/>
			<coords loc="14535 184206"/>
			<coords loc="11678 184349"/>
			<coords loc="11700 181241"/>
		</polygon>
	</zone>
	<zone name="[Hellbound_no_summon]" type="no_summon">
		<polygon>
			<coords loc="-32768 262144"/>
			<coords loc="-32768 229376"/>
			<coords loc="32768 229376"/>
			<coords loc="32768 262144"/>
		</polygon>
	</zone>
	<zone name="[Beleth_no_summon]" type="no_summon">
		<polygon>
			<coords loc="11214 205578 -10412 -5112"/>
			<coords loc="20607 205578 -10412 -5112"/>
			<coords loc="20648 220271 -10412 -5112"/>
			<coords loc="11172 220271 -10412 -5112"/>
		</polygon>
	</zone>
	<zone name="[Naia_no_summon]" type="no_summon">
		<polygon>
			<coords loc="-53384 242040"/>
			<coords loc="-53384 250488"/>
			<coords loc="-43528 250488"/>
			<coords loc="-43528 242040"/>
		</polygon>
	</zone>
	<zone name="[Gracia_no_summon]" type="no_summon">
		<polygon>
			<coords loc="-294912 294912"/>
			<coords loc="-294912 163840"/>
			<coords loc="-163840 163840"/>
			<coords loc="-163840 294912"/>
		</polygon>
	</zone>
	<zone name="[QA_no_summon]" type="no_summon">
		<polygon>
			<coords loc="-23176 185080 -6000 -5500"/>
			<coords loc="-20104 185080 -6000 -5500"/>
			<coords loc="-20104 177928 -6000 -5500"/>
			<coords loc="-23176 177928 -6000 -5500"/>
		</polygon>
	</zone>
	<zone name="[Talkin_inst_no]" type="no_summon">
		<polygon>
			<coords loc="49320 248376"/>
			<coords loc="49400 248536"/>
			<coords loc="47288 249624"/>
			<coords loc="43624 248872"/>
			<coords loc="42584 247848"/>
			<coords loc="41336 246232"/>
			<coords loc="43400 245048"/>
			<coords loc="43208 244328"/>
			<coords loc="47832 243224"/>
			<coords loc="48200 243208"/>
			<coords loc="48312 244664"/>
			<coords loc="48216 246248"/>
			<coords loc="48024 246552"/>
			<coords loc="48072 247336"/>
			<coords loc="48024 248664"/>
		</polygon>
		<restart_point>
			<coords loc="-84472 242744 -3728 8191"/>
		</restart_point>
	</zone>
	<zone name="[Harnake_no_summon]" type="no_summon">
		<polygon>
			<coords loc="-131072 131072"/>
			<coords loc="-98320 131072"/>
			<coords loc="-98320 163824"/>
			<coords loc="-131072 163824"/>
		</polygon>
	</zone>
</list>
