=== destruccionloca/L2Emurt-H5/dist/gameserver/config/default/phantom/jewels/phantomJewels.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (BotJewelObject)*>
<!ELEMENT BotJewelObject (earring_left|earring_right|ring_left|ring_right|necklace)*>
<!ATTLIST BotJewelObject
	classId CDATA #REQUIRED
	className CDATA #REQUIRED>
<!ELEMENT earring_left (#PCDATA)>
<!ATTLIST earring_left
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT earring_right (#PCDATA)>
<!ATTLIST earring_right
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT ring_left (#PCDATA)>
<!ATTLIST ring_left
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT ring_right (#PCDATA)>
<!ATTLIST ring_right
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>
<!ELEMENT necklace (#PCDATA)>
<!ATTLIST necklace
	id CDATA #REQUIRED
	enchant CDATA #REQUIRED
	is_random CDATA #IMPLIED>

=== destruccionloca/L2Emurt-H5/dist/gameserver/config/phantom/jewels/HellKnight.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE list SYSTEM "phantomJewels.dtd">
<list>
	<BotJewelObject classId="91" className="Hell Knight">
		<earring_left id="22175" enchant="6" is_random="false"/>
		<earring_right id="6656" enchant="6" is_random="false"/>
		<ring_left id="6658" enchant="6" is_random="false"/>
		<ring_right id="6660" enchant="6" is_random="false"/>
		<necklace id="6657" enchant="6" is_random="false"/> <!-- Valakas -->
	</BotJewelObject>
	<BotJewelObject classId="91" className="Hell Knight">
		<earring_left id="22175" enchant="6" is_random="false"/>
		<earring_right id="6656" enchant="6" is_random="false"/>
		<ring_left id="6658" enchant="6" is_random="false"/>
		<ring_right id="6660" enchant="6" is_random="false"/>
		<necklace id="8191" enchant="6" is_random="false"/> <!-- Frintezza -->
	</BotJewelObject>
	<BotJewelObject classId="91" className="Hell Knight">
		<earring_left id="22175" enchant="6" is_random="false"/>
		<earring_right id="6656" enchant="6" is_random="false"/>
		<ring_left id="22173" enchant="6" is_random="false"/> <!-- Усиленный Баюм -->
		<ring_right id="6660" enchant="6" is_random="false"/>
		<necklace id="8191" enchant="6" is_random="false"/> <!-- Frintezza -->
	</BotJewelObject>
	<BotJewelObject classId="91" className="Hell Knight">
		<earring_left id="22175" enchant="6" is_random="false"/>
		<earring_right id="6656" enchant="6" is_random="false"/>
		<ring_left id="22173" enchant="6" is_random="false"/> <!-- Усиленный Баюм -->
		<ring_right id="6660" enchant="6" is_random="false"/>
		<necklace id="6657" enchant="6" is_random="false"/> <!-- Валакас -->
	</BotJewelObject>
	<BotJewelObject classId="91" className="Hell Knight">
		<earring_left id="15718" enchant="6" is_random="false"/> <!-- Серьга Элегии -->
		<earring_right id="15718" enchant="6" is_random="false"/> <!-- Серьга Элегии -->
		<ring_left id="22173" enchant="6" is_random="false"/> <!-- Усиленный Баюм -->
		<ring_right id="6660" enchant="6" is_random="false"/>
		<necklace id="6657" enchant="6" is_random="false"/> <!-- Валакас -->
	</BotJewelObject>
 </list>
